version: "3.8"

services:
  db:
    image: postgres:14-alpine
    container_name: expensetracker_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: expensetracker
    volumes:
      - ./docker/data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    container_name: expensetracker_server
    build: 
      context: ./server
      dockerfile: ../docker/server/Dockerfile
    ports:
      - '4000:4000'
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run start:dev
